# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                                               #
#                                    CustomGuiForAnvil                                          #
#                           Created by eliotesta98 & xSavior_of_God                             #
#                                                                                               #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

Interface:
  Anvil:
    Title: "&0Repair & Name"
    OpenSound: ENTITY_ENDER_DRAGON_FLAP # ENDERDRAGON_WINGS <1.13
    Slots:
      - 'bbbbbbbbx'
      - 'bfbsbebrb'
      - 'nbbbbbbcb'
    Items:
      FirstItem:
        Letter: 'f'
        Name: ''
        Type: ''
        Texture: ''
        Lore: []
        SoundClick: ''
      SecondItem:
        Letter: 's'
        Name: ''
        Type: ''
        Texture: ''
        Lore: [ ]
        SoundClick: ''
      Submit:
        Letter: 'e'
        Name: '&2>&a&l> &a&lSUBMIT <&2<'
        Type: 'SUNFLOWER'
        Texture: ''
        Lore: [ ]
        SoundClick: ''
      NoResult:
        Letter: 'r'
        Name: ' '
        Type: 'BARRIER'
        Texture: ''
        Lore: [ ]
        SoundClick: ''
      Cost:
        Letter: 'c'
        Name: '&a&oEnchantment Cost: {exp}'
        Type: 'EXPERIENCE_BOTTLE'
        Texture: ''
        Lore: []
        SoundClick: ''
      Back:
        Letter: 'x'
        Name: '&7&l&oBACK TO ANVIL'
        Type: 'DAMAGED_ANVIL'
        Texture: ''
        Lore: [ ]
        SoundClick: ''
      Rename:
        Letter: 'n'
        Name: 'Coming Soon...'
        Type: 'NAME_TAG'
        Texture: ''
        Lore: [ ]
        SoundClick: ''
      Border:
        Letter: 'b'
        Name: " "
        Type: "GRAY_STAINED_GLASS_PANE" # STAINED_GLASS_PANE;7 <1.13
        Texture: '' # set to '' to disable
        Lore: [ ]
        SoundClick: ''

# you can use a different coloring by using a hexadecimal. for all messages Ex. &{#FFFF00}(yellow).
# Example for a command: '/cgfa &{#FFFF00}<reload>&{#000000} command reload Labyrinth plugin'
Messages:
  Prefix: '&eCustomAnvilGUI &r'
  Commands:
    Footer: '&7(&7&l(&c&l!&7&l)&7) &9[] optional value, <> required'
    Reload: '   &e/cagui &6<reload> &7for reload CustomGuiForAnvil plugin'
    Help: '   &e/cagui &6<help> &7for help commands'
  Success: {}
  Lists: {}
  Warnings: {}
  Errors:
    NoPlayer: '{prefix}&cYou are not a player'
    CommandNotFound: '{prefix}&cCommand not found'
    InsufficientPermission: '{prefix}&cInsufficient permission'
    InsufficientExperience: '{prefix}&cHEY! &7You don''t have much experience for enchant this items!'

Debug:
  # Commands execution
  Commands: false
  # Enabled of plugin
  Enabled: false
  # Disabled of plugin
  Disabled: false
  # Click in the gui
  ClickGui: false