# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                                               #
#                                    CustomGuiForAnvil                                          #
#                           Created by eliotesta98 & xSavior_of_God                             #
#                                                                                               #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

Configuration:
  # Set whether various plugins should be hooked into (i will also check if is enabled).
  Hooks:
    EcoEnchants: false
    AdvancedEnchantments: false

Interface:
  Anvil:
    Title: "&aAnvil"
    OpenSound: ENTITY_ENDER_DRAGON_FLAP # ENDERDRAGON_WINGS <1.13
    Slots:
      - 'bbbbbbbbb'
      - 'b b bb bb'
      - 'bbbbbbbbb'
    Items:
      Item:
        Letter: 'f'
        Name: ''
        Type: ''
        Texture: ''
        Lore: []
        SoundClick: ''
      Enchant:
        Letter: 's'
        Name: ''
        Type: ''
        Texture: ''
        Lore: [ ]
        SoundClick: ''
      Result:
        Letter: 'r'
        Name: ''
        Type: ''
        Texture: ''
        Lore: [ ]
        SoundClick: ''
      Border:
        Letter: 'b'
        Name: " "
        Type: GRAY_STAINED_GLASS_PANE # STAINED_GLASS_PANE;7 <1.13
        Texture: '' # set to '' to disable
        Lore: [ ]
        SoundClick: ''

# you can use a different coloring by using a hexadecimal. for all messages Ex. &{#FFFF00}(yellow).
# Example for a command: '/cgfa &{#FFFF00}<reload>&{#000000} command reload Labyrinth plugin'
Messages:
  Prefix: '&eCustomGuiForAnvil &r'
  Commands:
    Footer: '&7(&7&l(&c&l!&7&l)&7) &9[] optional value, <> required'
    Reload: '   &e/cgfa &6<reload> &7for reload CustomGuiForAnvil plugin'
    Help: '   &e/cgfa &6<help> &7for help commands'
  Success: {}
  Lists: {}
  Warnings: {}
  Errors:
    NoPlayer: '{prefix}&cYou are not a player'
    CommandNotFound: '{prefix}&cCommand not found'
    InsufficientPermission: '{prefix}&cInsufficient permission'

Debug:
  # Commands execution
  Commands: false
  # Enabled of plugin
  Enabled: false
  # Disabled of plugin
  Disabled: false
  # Click in the gui
  ClickGui: false