# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #    
#                                                                                               #
#                                         AnvilPlus                                             #
#                           Created by eliotesta98 & xSavior_of_God                             #
#                                                                                               #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #   

Configuration:
  # Set whether various plugins should be hooked into (i will also check if is enabled).
  Hooks:
    EcoEnchants: false
    AdvancedEnchantments: false


# you can use a different coloring by using a hexadecimal. for all messages Ex. &{#FFFF00}(yellow).
# Example for a command: '/labyrinth &{#FFFF00}<reload>&{#000000} command reload Labyrinth plugin'
Messages:
  Prefix: '&eAnvilPlus &r'
  Commands:
    Footer: '&7(&7&l(&c&l!&7&l)&7) &9[] optional value, <> required'
    Reload: '   &e/anvilplus &6<reload> &7for reload AnvilPlus plugin'
    Help: '   &e/anvilplus &6<help> &7for help commands'
  Success: {}
  Lists: {}
  Warnings: {}
  Errors:
    NoPlayer: '{prefix}&cYou are not a player'
    CommandNotFound: '{prefix}&cCommand not found'
    InsufficientPermission: '{prefix}&cInsufficient permission'

Debug:
  # Commands time execution
  Commands: false
  # Enabled time execution
  Enabled: false
  # Disabled time execution
  Disabled: false