# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                                               #
#                                      CustomAnvilGUI                                           #
#                           Created by eliotesta98 & xSavior_of_God                             #
#                                                                                               #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

Configuration:
  Hooks:
    Floodgate: false

  # This section is for configuring how much is the possibility of anvil damage at every use.
  # For default, there is 1/8 (12%) possibility to damage the anvil at each use
  AnvilDamage:
    Damage: 12

  # Configure if you want directly the rename of item or reopen the anvil for rename an item
  DirectRename: false

  # This sound is triggered when an anvil change stage
  AnvilSound:
    SoundName: 'minecraft:block.anvil.use'
    Volume: 100
    Pitch: 0.6

Interface:
  Anvil:
    Title: "&0Repair & Name"
    OpenSound:
      SoundName: 'minecraft:entity.allay.item_thrown'
      Volume: 100
      Pitch: 0.6
    Slots:
      - 'tbbbbbbbx'
      - 'bfbsbebrb'
      - 'nbbbbbbcb'
    Items:
      FirstItem:
        Letter: 'f'
        Name: ''
        Type: ''
        Texture: ''
        Lore: [ ]
        SoundClick: ''
      SecondItem:
        Letter: 's'
        Name: ''
        Type: ''
        Texture: ''
        Lore: [ ]
        SoundClick: ''
      Submit:
        Letter: 'e'
        Name: '&2>&a&l> &a&lSUBMIT <&2<'
        Type: 'SUNFLOWER'
        Texture: ''
        Lore: [ ]
        SoundClick: ''
      NoResult:
        Letter: 'r'
        Name: '{message}'
        Type: 'BARRIER'
        Texture: ''
        Lore: [ ]
        SoundClick: ''
      Cost:
        Letter: 'c'
        Name: '&a&oEnchantment Cost: {exp}'
        Type: 'EXPERIENCE_BOTTLE'
        Texture: ''
        Lore: [ ]
        SoundClick: ''
      Back:
        Letter: 'x'
        Name: '&7&l&oBACK TO ANVIL'
        Type: 'DAMAGED_ANVIL'
        Texture: ''
        Lore: [ ]
        SoundClick: ''
      Rename:
        Letter: 'n'
        Name: '&e>&e&l> &e&lRENAME <&e<'
        Type: 'NAME_TAG'
        Texture: ''
        Lore: [ ]
        SoundClick: ''
      Fix:
        Letter: 't'
        Name: '&b>&b&l> &b&lFIX <&b<'
        Type: 'DIAMOND_PICKAXE'
        Texture: ''
        Lore:
          - "&bRepair items in your inventory"
          - "&b&l> &bLeft Click: repair the item in your main hand"
          - "&b&l> &bRight Click: repair all items in your inventory"
        SoundClick: ''
      Border:
        Letter: 'b'
        Name: " "
        Type: "GRAY_STAINED_GLASS_PANE" # STAINED_GLASS_PANE;7 <1.13
        Texture: '' # set to '' to disable
        Lore: [ ]
        SoundClick: ''
    Floodgate: { }

  Rename:
    Title: "Renaming..."
    OpenSound: ENTITY_ENDER_DRAGON_FLAP # ENDERDRAGON_WINGS <1.13
    Slots: [ ]
    Items: { }
    Floodgate:
      1:
        Type: 'Input'
        Label: 'Item Name'
        Placeholder: 'Diamond Sword'
        DefaultText: ''


# you can use a different coloring by using a hexadecimal. for all messages Ex. &{#FFFF00}(yellow).
# Example for a command: '/cagui &{#FFFF00}<reload>&{#000000} command reload Labyrinth plugin'
Messages:
  Prefix: '&eCustomAnvilGUI &r'
  Commands:
    Footer: '&7(&7&l(&c&l!&7&l)&7) &9[] optional value, <> required'
    Reload: '   &e/cagui &6<reload> &7for reload CustomGuiForAnvil plugin'
    Help: '   &e/cagui &6<help> &7for help commands'
  Success:
    Rename: '{prefix}&aTool name has been successfully registered, please now reopen the anvil, place your tool in the anvil and click on Rename button'
  Results:
    NoItem: '&cHEY! &7You don''t have much experience for enchant this items!'
  Lists: { }
  Warnings: { }
  Info:
    Rename: '{prefix}&7Please write the name of your tool in chat'
  Errors:
    NoPlayer: '{prefix}&cYou are not a player'
    CommandNotFound: '{prefix}&cCommand not found'
    InsufficientPermission: '{prefix}&cInsufficient permission'
    InsufficientExperience: '{prefix}&cHEY! &7You don''t have much experience for enchant this items!'

Debug:
  # Commands execution
  Commands: false
  # Enabled of plugin
  Enabled: false
  # Disabled of plugin
  Disabled: false
  # Click in the gui
  ClickGui: false
  # API
  API: false